# Generated by Django 5.1.3 on 2025-04-02 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.SmallIntegerField(choices=[(1, '技术类'), (2, '产品类'), (3, '运营类'), (4, '设计类')], default=1, verbose_name='职位类别')),
                ('job_name', models.CharField(max_length=100, verbose_name='职位名称')),
                ('job_location', models.SmallIntegerField(choices=[(1, '北京'), (2, '上海'), (3, '广州')], default=1, verbose_name='工作地点')),
                ('job_responsibility', models.TextField(verbose_name='岗位职责')),
                ('job_requirements', models.TextField(verbose_name='任职要求')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
        ),
    ]
