# Generated by Django 5.1.3 on 2025-04-03 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_location',
            field=models.SmallIntegerField(choices=[(0, '北京'), (1, '上海'), (2, '深圳'), (3, '杭州'), (4, '广州')], default=1, verbose_name='工作地点'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.SmallIntegerField(choices=[(0, '技术类'), (1, '产品类'), (2, '运营类'), (3, '设计类'), (4, '市场营销类')], default=1, verbose_name='职位类别'),
        ),
    ]
